### ISSUE TITLE
NMS not working in 1.18.x

### ISSUE THREAD

**Issue by MarkC0x** [TheBrunoRM/Skywars#4]
This is a really awesome plugin -- thank you -- but it doesn't appear to be fully compatible with the new 1.18.x Minecraft server versions unfortunately.  I think this may be due to NMS package incompatibilities, but am not 100% sure.

1. Install the plugin into your Minecraft 1.18.1 or 1.18.2 server
2. Start the server

```
[Server thread/INFO]: [Skywars] Enabling Skywars v0.2.8
[Server thread/INFO]: [Skywars-NMS-Debug] Loading old ChatSerializer
[Server thread/INFO]: [Skywars-NMS-Debug] Loading new ChatSerializer
[Server thread/INFO]: [Skywars-NMS-Debug] Could not load ChatSerializer
[Server thread/INFO]: [Skywars-NMS-Debug] Loading ChatBaseComponent Interface
[Server thread/INFO]: [Skywars-NMS-Debug] Could not load ChatBaseComponent Interface
[Server thread/INFO]: [Skywars-NMS-Debug] Loading PacketPlayOutTitle
[Server thread/INFO]: [Skywars-NMS-Debug] Could not load PacketPlayOutTitle
[Server thread/INFO]: [Skywars-NMS-Debug] Loading PacketPlayOutChat
[Server thread/INFO]: [Skywars-NMS-Debug] Could not load PacketPlayOutChat
[Server thread/INFO]: [Skywars-NMS-Debug] Loading old EnumTitleAction
[Server thread/INFO]: [Skywars-NMS-Debug] Loading new EnumTitleAction
[Server thread/INFO]: [Skywars-NMS-Debug] Could not load EnumTitleAction
[Server thread/INFO]: [Skywars-NMS-Debug] Loading ChatMessageType
[Server thread/INFO]: [Skywars-NMS-Debug] Could not find ChatMessageType
```

3. Start a Skywars game, and then you see a bunch of NPE's in the log indicating that `chatSerializer` in NULL, generated most likely from the code below from `NMSHandler.java`

```	public void sendTitle(Player player, String title, String subtitle, int fadeIn, int stay, int fadeOut) {
		try {

			Method a = chatSerializer.getMethod("a", String.class);
			...
```

A clear and concise description of what you expected to happen: No NPEs during the game

**Versions (please complete the following information):**
 - Plugin version: 0.28
 - Server version: 1.18.2

It would be really cool if this plugin could be updated for the latest Minecraft server versions 😄

**Comment by TheBrunoRM** [comment]
I haven't tested the plugin on 1.18+ versions yet since my pc doesn't run Minecraft on these versions.
It seems that in fact, the plugin can't find the NMS for 1.18. I suppose the fix would be simply adding the missing NMS for 1.18+ versions.
I would like to know if there are any other issues apart from this in newer versions.
Thanks for reporting this!

**Comment by MarkC0x** [comment]
Hey @TheBrunoRM -- wow, that was a fast response 😄 

I am acting as a bit of a proxy for my daughter here on this one LOL, but she did tell me (and I quote) that the plugin is "absolutely awesome" and plays with her friends on our Minecraft server.  I think it plays well except for the NPEs, but I can ask her to do more testing and report any errors she sees on these later server versions.

Would it be possible to build a test `JAR` against the newer NMS packages, and we could try that for you?

Cheers

**Comment by TheBrunoRM** [comment]
I just checked the NMS for the 1.18+ versions and it seems that they removed them. So I guess the fix wouldn't be as easy as adding the NMS (since they don't exist), but it would need to use the code from the bukkit API for that version.
I will try that, but I'm not sure of how well it will work.

**Comment by TheBrunoRM** [comment]
I couldn't get eclipse to work with the 1.18 Bukkit jar file. I tried installing Java SDK 17 and also couldn't. For some reason when I open the installer .exe it doesn't do anything.
I will try making the code for it to work but I'm not sure if I will be able to make a build or test with it.

**Comment by MarkC0x** [comment]
Hmm, that's a shame.  I run on MacOS with IntelliJ so haven't run into either of those issues.  I may try and import your Eclipse project into IntelliJ this coming week to see if I can recompile against the new Spigot dependencies, but this may be tricky for me as I am not really into Minecraft plugin development.

I do appreciate your willingness to help though and your quick responses to my questions 👍

**Comment by TheBrunoRM** [comment]
That's great! I can't do anything at the moment. I already tried my best to make Java install but I guess I will have to keep trying until I find a solution that works for me.
I made some code for this, maybe you can try it with the 1.18 JAR to see if it works.

On the NMS package, I made an NMS interface class like this:
```
public interface NMS {

	public void sendParticles(Player player, Location loc, String particle, int amount);
	public void sendActionbar(Player player, String text);
	public void sendTitle(Player player, String title);
	public void sendTitle(Player player, String title, String subtitle);
	public void sendTitle(Player player, String title, String subtitle, int fadeIn, int stay, int fadeOut);
	
}
```

Then I made a class that implements NMS for the 1.18 methods (I didn't do the `sendTitle` one yet):
```
public class OnePointEighteen implements NMS {

	@Override
	public void sendParticles(Player player, Location loc, String particle, int amount) {
		//player.spawnParticle(Particle.valueOf(particle), loc, amount);
	}

	@Override
	public void sendActionbar(Player player, String text) {
		//player.sendMessage(ChatMessageType.ACTION_BAR, new TextComponent(text));
	}

	@Override
	public void sendTitle(Player player, String title) {
	}

	@Override
	public void sendTitle(Player player, String title, String subtitle) {
	}

	@Override
	public void sendTitle(Player player, String title, String subtitle, int fadeIn, int stay, int fadeOut) {
	}

}
```

Then I just made the NMSHandler implement NMS.
The idea is that when the plugin starts, on the main class, when setting the NMSHandler variable, either use the NMSHandler or use the 1.18 class according to the NMS version.

I hope you can make this work!

**Comment by TheBrunoRM** [comment]
Good news! I uninstalled all Java versions using an uninstaller and I finally could install Java 17 and open Minecraft 1.18.2!
I will try making this work.

**Comment by TheBrunoRM** [comment]
Update: I'm trying to set up a plugin using Maven to import the 1.18 Spigot JAR as a dependency.

**Comment by MarkC0x** [comment]
That's great news @TheBrunoRM and good progress 🎉   

I have only got as far as getting the plugin to be able to compile through Intellij and Maven.  I found that when you update the Spigot dependancies to the `1.18.x` levels then there is an amount of code refactoring needed.

I am watching intently as to how far you get and crossing my fingers 🤞 

Thanks!

**Comment by TheBrunoRM** [comment]
Update: I made a simple plugin using NMS with Maven, and it seems to be working!
So I think I am going to set up Maven in the plugin so it works with the 1.8 Spigot JAR. Although I am not sure if it will still work with other versions.
Before doing anything on this project, I am going to try things with a test plugin. I'll update when I get everything working.

**Comment by TheBrunoRM** [comment]
Update: I got the titles working! No more NPEs for that.
But there is a problem: I'm trying to find a way to send actionbar messages in 1.18, but I can't find any!
When I try using the `sendMessage` method that grabs a `BaseComponent`, I get a `NoClassDefFoundError` saying that it can't find that class :(
At least the titles are working now! I'm going to make a commit.

Also, I didn't even need to add the Maven stuff or even the 1.18 JAR!

**Comment by TheBrunoRM** [comment]
I built the new release! @MarkC0x I would be very grateful if you could test it and tell me if it works!
https://github.com/TheBrunoRM/Skywars/releases/tag/v0.2.9

**Comment by MarkC0x** [comment]
You bet @TheBrunoRM -- let me get that new `Jar` installed on the server and report back to you.  I may need a couple of hours though until my daughter gets home later for more of a stress test 🙂

**Comment by TheBrunoRM** [comment]
Good news!! I made the actionbar work on a test plugin I made for the 1.18.2 version. Now all I need to do is to implement this on the plugin and it should be good to go!

**Comment by MarkC0x** [comment]
Hey @TheBrunoRM -- your latest plugin release looks good and there are no more NPEs thrown when starting the game, nice work!  We'll keep testing on our side to see if anything else comes up, but so far so good 👍

**Comment by TheBrunoRM** [comment]
Thank you very much! I will try to implement the actionbar tomorrow, and I think that's it regarding NMS stuff.

**Comment by TheBrunoRM** [comment]
I will be closing this since it seems that it has been fixed in c49e541805656af6c4379ecfa5d3cd66349274e7, and now works flawlessly.
Thanks for your feedback!
